services:
  app:
    build:
      context: . # Assumes Dockerfile is in the same directory as docker-compose.yml
    ports:
      - 127.0.0.1:${SERVER_PORT}:3000 # Host machine port defined in .env file
    env_file:
      - path: .env
        required: true
      - path: .env.development
        required: false
    environment:
      NODE_ENV: production
    depends_on:
      - db

  # PostgreSQL database
  db:
    image: postgres:latest
    env_file:
      - path: .env
        required: true
      - path: .env.development
        required: false
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
